version: '3'
services:
  db:
    image: postgres
    volumes:
      - volume-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  web: &ruby_base
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - volume-bundle:${API_ROOT}/vendor/bundle
      - ./web:${API_ROOT}
    ports:
      - "${API_PORT}:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      RAILS_LOG_TO_STDOUT: 'true'
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    command: npm run serve
    ports:
      - "${FRONT_PORT}:8080"
    volumes:
      - volume-node-modules:${FRONT_ROOT}/node_modules
      - ./front:${FRONT_ROOT}
volumes:
  volume-db-data:
    driver: local
  volume-bundle:
    driver: local
  volume-node-modules:
    driver: local
