FROM ruby:2.7

ARG API_ROOT=/app
ENV API_ROOT ${API_ROOT}
WORKDIR ${API_ROOT}

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

COPY Gemfile ${API_ROOT}/Gemfile
COPY Gemfile.lock ${API_ROOT}/Gemfile.lock

RUN bundle config set path 'vendor/bundle' && bundle install
COPY . ${API_ROOT}

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
